baseurl = "http://yourdomain.com"
languageCode = "en-us"
title = "Sino-Herbs"
canonifyUrls = "true"

[params]
    description = "Chinesische Heilpflanzenhaus"
    custom_css = ["css/local.css"]

[[params.social]]
    title = "Kontakt"
    icon = "envelope-o"
    url = "mailto:info@sino-herbs.de"
